name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
        env:
          TRANSLATION_KEY: ${{ secrets.TRANSLATION_KEY}}
          REGION: ${{ secrets.REGION }}
          TTS_KEY: ${{ secrets.TTS_KEY }}
      - run: npm start
